In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
os.chdir('..')

In [3]:
from Bio import SeqIO

In [4]:
import re
import random
import numpy as np
import pandas as pd
from itertools import product
from mofiwo.utility import generate_utr_from_cdna_cds, load_rna_fasta_zipfile
from mofiwo.analysis import generate_k_mer, generate_feature_by_kmer_loc

In [ ]:
from sklearn import linear_model
from sklearn import svm
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [18]:
_folder = r'C:\Users\by003457\workspace\rnamotif\samples'

In [19]:
zip_cdna = os.path.join(_folder,'s1_cdna.zip')
zip_cds = os.path.join(_folder,'s1_cds.zip')

In [20]:
dic_cdna = load_rna_fasta_zipfile(zip_cdna)
dic_cds = load_rna_fasta_zipfile(zip_cds)

In [21]:
dic_utr = generate_utr_from_cdna_cds(dic_cdna, dic_cds)

CDNA contains 2074 sequences more than CDS
Can not find coding sequence(CDS) position in ENSMUST00000208477
Can not find coding sequence(CDS) position in ENSMUST00000146044
Can not find coding sequence(CDS) position in ENSMUST00000144529
Can not find coding sequence(CDS) position in ENSMUST00000143074
Can not find coding sequence(CDS) position in ENSMUST00000194381
Can not find coding sequence(CDS) position in ENSMUST00000042627
Can not find coding sequence(CDS) position in ENSMUST00000131696
Can not find coding sequence(CDS) position in ENSMUST00000175755
Can not find coding sequence(CDS) position in ENSMUST00000206830
Can not find coding sequence(CDS) position in ENSMUST00000206315
Can not find coding sequence(CDS) position in ENSMUST00000140178
Can not find coding sequence(CDS) position in ENSMUST00000171426
Can not find coding sequence(CDS) position in ENSMUST00000125901
Can not find coding sequence(CDS) position in ENSMUST00000155278
Can not find coding sequence(CDS) position in E

Can not find coding sequence(CDS) position in ENSMUST00000208322
Can not find coding sequence(CDS) position in ENSMUST00000148643
Can not find coding sequence(CDS) position in ENSMUST00000163183
Can not find coding sequence(CDS) position in ENSMUST00000171106
Can not find coding sequence(CDS) position in ENSMUST00000075540
Can not find coding sequence(CDS) position in ENSMUST00000136663
Can not find coding sequence(CDS) position in ENSMUST00000132603
Can not find coding sequence(CDS) position in ENSMUST00000082396
Can not find coding sequence(CDS) position in ENSMUST00000161428
Can not find coding sequence(CDS) position in ENSMUST00000126794
Can not find coding sequence(CDS) position in ENSMUST00000129449
Can not find coding sequence(CDS) position in ENSMUST00000153777
Can not find coding sequence(CDS) position in ENSMUST00000156442
Can not find coding sequence(CDS) position in ENSMUST00000148204
Can not find coding sequence(CDS) position in ENSMUST00000092663
Can not find coding seque

Can not find coding sequence(CDS) position in ENSMUST00000125981
Can not find coding sequence(CDS) position in ENSMUST00000112055
Can not find coding sequence(CDS) position in ENSMUST00000166719
Can not find coding sequence(CDS) position in ENSMUST00000141497
Can not find coding sequence(CDS) position in ENSMUST00000173967
Can not find coding sequence(CDS) position in ENSMUST00000199174
Can not find coding sequence(CDS) position in ENSMUST00000142701
Can not find coding sequence(CDS) position in ENSMUST00000162855
Can not find coding sequence(CDS) position in ENSMUST00000044638
Can not find coding sequence(CDS) position in ENSMUST00000156096
Can not find coding sequence(CDS) position in ENSMUST00000143083
Can not find coding sequence(CDS) position in ENSMUST00000164108
Can not find coding sequence(CDS) position in ENSMUST00000195151
Can not find coding sequence(CDS) position in ENSMUST00000156001
Can not find coding sequence(CDS) position in ENSMUST00000085094
Can not find coding seque

Can not find coding sequence(CDS) position in ENSMUST00000167507
Can not find coding sequence(CDS) position in ENSMUST00000205870
Can not find coding sequence(CDS) position in ENSMUST00000113111
Can not find coding sequence(CDS) position in ENSMUST00000109941
Can not find coding sequence(CDS) position in ENSMUST00000204915
Can not find coding sequence(CDS) position in ENSMUST00000197764
Can not find coding sequence(CDS) position in ENSMUST00000141902
Can not find coding sequence(CDS) position in ENSMUST00000190061
Can not find coding sequence(CDS) position in ENSMUST00000178282
Can not find coding sequence(CDS) position in ENSMUST00000176726
Can not find coding sequence(CDS) position in ENSMUST00000202648
Can not find coding sequence(CDS) position in ENSMUST00000208943
Can not find coding sequence(CDS) position in ENSMUST00000082421
Can not find coding sequence(CDS) position in ENSMUST00000172122
Can not find coding sequence(CDS) position in ENSMUST00000127514
Can not find coding seque

Can not find coding sequence(CDS) position in ENSMUST00000172321
Can not find coding sequence(CDS) position in ENSMUST00000125774
Can not find coding sequence(CDS) position in ENSMUST00000156111
Can not find coding sequence(CDS) position in ENSMUST00000151184
Can not find coding sequence(CDS) position in ENSMUST00000004986
Can not find coding sequence(CDS) position in ENSMUST00000082407
Can not find coding sequence(CDS) position in ENSMUST00000146307
Can not find coding sequence(CDS) position in ENSMUST00000075573
Can not find coding sequence(CDS) position in ENSMUST00000174294
Can not find coding sequence(CDS) position in ENSMUST00000110904
Can not find coding sequence(CDS) position in ENSMUST00000082405
Can not find coding sequence(CDS) position in ENSMUST00000134660
Can not find coding sequence(CDS) position in ENSMUST00000145013
Can not find coding sequence(CDS) position in ENSMUST00000125034
Can not find coding sequence(CDS) position in ENSMUST00000189820
Can not find coding seque

In [22]:
dic_seq = dict()
for k,v in dic_utr.items():
    dic_seq.update({k: {'CDS': dic_cds[k].seq, 'UT3': v['utr3'], 'UT5': v['utr5']}})

In [23]:
ret = generate_feature_by_kmer_loc(dic_seq, need_log=True)

# proceed: 100
# proceed: 200
# proceed: 300
# proceed: 400
# proceed: 500
# proceed: 600
# proceed: 700
# proceed: 800
# proceed: 900
# proceed: 1000
# proceed: 1100
# proceed: 1200
# proceed: 1300
# proceed: 1400
# proceed: 1500
# proceed: 1600
# proceed: 1700
# proceed: 1800
# proceed: 1900
# proceed: 2000
# proceed: 2100
# proceed: 2200
# proceed: 2300
# proceed: 2400
# proceed: 2500
# proceed: 2600
# proceed: 2700
# proceed: 2800
# proceed: 2900
# proceed: 3000
# proceed: 3100
# proceed: 3200
# proceed: 3300
# proceed: 3400
# proceed: 3500
# proceed: 3600
# proceed: 3700
# proceed: 3800
# proceed: 3900
# proceed: 4000
# proceed: 4100
# proceed: 4200
# proceed: 4300
# proceed: 4400
# proceed: 4500
# proceed: 4600
# proceed: 4700
# proceed: 4800
# proceed: 4900
# proceed: 5000
# proceed: 5100
# proceed: 5200
# proceed: 5300
# proceed: 5400
# proceed: 5500
# proceed: 5600
# proceed: 5700
# proceed: 5800
# proceed: 5900
# proceed: 6000
# proceed: 6100
# proceed: 6200
# proceed: 6300
#

In [24]:
df = pd.DataFrame(ret)

In [25]:
df.shape

(4032, 7252)

In [26]:
df.to_parquet('./notebook/feature_intestine.gzip.parquet',compression='gzip')

In [15]:
df= pd.read_parquet('./notebook/feature_intestine.gzip.parquet')

In [27]:
df.fillna(0.0,inplace=True)

In [28]:
df_s1 = pd.read_excel(os.path.join(_folder,'aan2399_table_S1.xlsx'))

In [167]:
round(-1.4)

-1

In [168]:
df_s1 = df_s1[df_s1.target_id.isin(list(df.columns))]
df_s1['b2'] = df_s1.b.apply(lambda x: round(x))

In [214]:
cols = list(df_s1[(abs(df_s1.b2) < 4) & (df_s1.mean_obs > 3.5) & (df_s1.qval < 0.2)].target_id)
len(cols)

In [202]:
df_x = df[cols]
df_y = {x: int(df_s1[df_s1.target_id == x]['b2']) for x in cols}
df_y = pd.DataFrame(df_y, index=[0])

In [205]:
df_x2 = df_x.T
df_y2 = df_y.T
df_y2.columns = ['Class']
df_xy = pd.merge(df_x2,df_y2, left_index=True, right_index=True)

In [206]:
df_xy.shape

(475, 4033)

In [207]:
X = df_xy.iloc[:,:-1].values
y = df_xy.iloc[:,-1].values

In [208]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [209]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [210]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import NearestNeighbors

regressor = RandomForestClassifier(n_estimators=1000, random_state=0)
# regressor = NearestNeighbors(n_neighbors=100, algorithm='ball_tree')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [212]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 0  0  0  0  1  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  4  1 12  0  0]
 [ 0  0  0  0 13  0  0]
 [ 0  0  0  0 59  0  0]
 [ 0  0  0  0  3  0  0]
 [ 0  0  0  0  1  0  0]]
              precision    recall  f1-score   support

          -3       0.00      0.00      0.00         1
          -2       0.00      0.00      0.00         1
          -1       0.80      0.24      0.36        17
           0       0.00      0.00      0.00        13
           1       0.66      1.00      0.80        59
           2       0.00      0.00      0.00         3
           3       0.00      0.00      0.00         1

    accuracy                           0.66        95
   macro avg       0.21      0.18      0.17        95
weighted avg       0.55      0.66      0.56        95

0.6631578947368421


c:\users\by003457\workspace\mofiwo\env\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\by003457\workspace\mofiwo\env\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\by003457\workspace\mofiwo\env\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
